version: '2'
services:
  laravel-app:
    container_name: laravel-app
    build: .
    ports:
     - "8000:80"
    volumes:
     - ./:/usr/share/nginx
    networks:
      - app-network
  mysql-app:
   container_name: mysql-app
   image: mysql:5.7.22
   ports:
     - "3306:3306"
   environment:
     MYSQL_DATABASE: laravel
     MYSQL_ROOT_PASSWORD: laravel
   networks:
     - app-network
networks:
  app-network:
   driver: bridge
